[package]
name = "shiguredo_audio_toolbox"
version = "2026.1.0-canary.0"
edition = "2024"
rust-version = "1.88"
authors = ["Shiguredo Inc."]
license = "Apache-2.0"
description = "Rust bindings for Apple Audio Toolbox audio encoders and decoders"
homepage = "https://github.com/shiguredo/audio-toolbox-rs"
repository = "https://github.com/shiguredo/audio-toolbox-rs"
keywords = ["audio", "aac", "encoder", "decoder", "macos"]
categories = ["multimedia::audio", "os::macos-apis"]
readme = "README.md"
build = "build.rs"
include = ["/src/**", "/build.rs", "/README.md", "/LICENSE"]

[dependencies]

[build-dependencies]
bindgen = "0.72.0"

[dev-dependencies]
shiguredo_mp4 = "2026.2.0-canary.3"
